### PR TITLE
setup mockito and espresso on android tests

### PR DESCRIPTION
**Pull request by rockycamacho**

### CODE REVIEW

**Comment by alouanemed** [comment]
Thanks for the PR @rockycamacho, but you added the wrong Mockito depedency  : 
Here is the correct one : 
`dependencies { testCompile "org.mockito:mockito-core:2.+" }`

**Comment by rockycamacho** [comment]
mockito for android has some issues
https://github.com/mockito/mockito/issues/706

linkedin dexmaker works for dalvik and already has a dependency on mockito

**Comment by alouanemed** [comment]
The issue you mentioned is closed and solved and currently, we don't need dexmaker.

**Comment by rockycamacho** [comment]
updated my pr. 

thanks

**Pull request merged**
